version: '3'
services:
  flask:
    image: testimages
    build:
      context: ./
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NAME=${NAME}
      - ENV=${ENV}
      - PORT=${PORT}